version: "3.8"
name: fullstackhero
services:
  dotnet-webapi:
    image: dotnet-webapi-starter-kit:latest
    container_name: dotnet-webapi
    networks:
      - fullstackhero
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5010
      - ASPNETCORE_HTTPS_PORT=5100
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - DatabaseOptions__ConnectionString=Server=postgres;Port=5433;Database=fshdb;User Id=posgresqladmin;Password=posgresqladmin
      - DatabaseOptions__Provider=postgresql
      - JwtOptions__Key=S0M3RAN0MS3CR3T!1!MAG1C!1!
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 5100:5100
      - 5010:5010
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    networks:
      - fullstackhero
    environment:
      - POSTGRES_USER=posgresqladmin
      - POSTGRES_PASSWORD=posgresqladmin
      - PGPORT=5433
    ports:
      - 5433:5433
    volumes:
      - postgresdata:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgresdata:
networks:
  fullstackhero:
    name: fullstackhero
