apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "maxiar-dotnetstarterkit-blazor.labels" . | nindent 4 }}
  name: {{ include "maxiar-dotnetstarterkit-blazor.fullname" . }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "maxiar-dotnetstarterkit-blazor.selectorLabels" . | nindent 6 }}
  type: ClusterIP
