name: build
on:
  push:
    branches: ["v2"]
  pull_request:
    branches: ["v2"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: restore dependencies
        run: dotnet restore ./api/FSH.WebApi.sln
      - name: build
        run: dotnet build ./api/FSH.WebApi.sln --no-restore
      - name: test
        run: dotnet test ./api/FSH.WebApi.sln --no-build --verbosity normal
  docker:
    name: docker
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: publish docker image
        working-directory: ./
        run: |
          dotnet publish ./api/FSH.WebApi.sln -c Release -p:ContainerRepository=${{ secrets.DOCKER_USERNAME }}/dotnet-webapi-starter-kit -p:RuntimeIdentifier=linux-x64
          docker push ${{ secrets.DOCKER_USERNAME }}/dotnet-webapi-starter-kit --all-tags
